-- AlterTable
ALTER TABLE "CharacterFightStat" ALTER COLUMN "value" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "CharacterRaidInfo" ALTER COLUMN "attendance_percentage" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "normalization_time_allies" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "CharacterRaidStat" ALTER COLUMN "value" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "FightStat" ALTER COLUMN "value" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "RaidStat" ALTER COLUMN "value" SET DATA TYPE DOUBLE PRECISION;
